name: flutter_dashboard_3
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  sqflite_common_ffi: ^2.3.6
  path: ^1.9.1
  excel: ^4.0.6
  file_picker: ^10.2.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  pdf: ^3.11.3
  printing: ^5.14.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
